import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Perfil | E-Eco",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return children;
}