import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Produtos | E-Eco",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return children;
}